title: Anik Pramanik
logo: assets/img/profile.jpg
header:
  logo_size: 90px # You can adjust the pixel size here
description: Looking for a PhD Position | Machine Learning | Healthcare Analytics | Image Processing | NLP
#show_downloads: true
theme:jekyll-theme-vanguard
