title: Anik Pramanik
logo: assets/img/profile.jpg 
header: 
      logo_size: 80px # You can adjust the pixel size here
description: Data Engineer | Healthcare Analytics Researcher | Image Processing | Large Language Models
#show_downloads: true
theme: jekyll-theme-minimal
