title: Anik Pramanik
logo: assets/img/profile.jpg 
header: 
      logo_size: 80px # You can adjust the pixel size here
description: Machine Learning | Healthcare Analytics | Large Language Models (LLMs) |  Federated Learning 
#show_downloads: true
theme: jekyll-theme-minimal
